### ISSUE TITLE
Can this work with a local installation of instant-markdown-d?

### ISSUE THREAD

**Issue by infokiller** [suan/vim-instant-markdown#103]
I noticed the FAQ mentions that it should be installed globally (using `-g`), however many people (including myself) are reluctant to install things on the system and prefer to have them isolated locally.

Thanks!

**Comment by balta2ar** [comment]
@infokiller I've installed it locally and ran nvim as follows:
``` bash
PATH=$PATH:$HOME/node_modules/instant-markdown-d nvim README.md
```
And it worked fine.

**Comment by suan** [comment]
Yeah `vim-instant-markdown` and `instant-markdown-d` are meant to be general purpose utilities that can be called from anywhere (similar to eg `jq`) so it makes sense to install globally. And what @balta2ar shared works.

**Comment by infokiller** [comment]
Installing globally is not always possible (without root access) or desirable (to avoid changing the system).
