### ISSUE TITLE
vimL error in function <SNR>25_previewMarkdown

### ISSUE THREAD

**Issue by lifeich1** [suan/vim-instant-markdown#111]
The error is _E488_.

I found an extra `)` in line **157**. When I remove it, the error is fixed. Maybe it is not considered as a problem?

**Comment by suan** [comment]
Thanks! I'll look into it.

**Comment by IanEdington** [comment]
This has been fixed with pull request #106

**Comment by suan** [comment]
As @IanEdington mentioned, it's been fixed in master
