### ISSUE TITLE
Scrolling synchronisation

### ISSUE THREAD

**Issue by PhilippeLeroux** [suan/vim-instant-markdown#114]
Hi,

Your plugin is very useful, but if possible can you synchronize the scrolling between [G]vim and the navigator ?

Regards.

**Comment by hitzhangjie** [comment]
A good idea, I noticed iaWriter in OSX and IntelliJ IDEA markdown plugin support the feature that focusing on the part which is being edited. If suan add this feature, it'll be better for vim users.

**Comment by charliepotts** [comment]
There's even a [pull request](https://github.com/suan/vim-instant-markdown/pull/74) for this, just needs to be merged.

**Comment by ashwinvis** [comment]
Fixed in #74

**Comment by Kevin-Mok** [comment]
This doesn't seem to work for me on Firefox or Chromium on Linux.

**Comment by ashwinvis** [comment]
@Kevin-Mok please open a new issue and follow the debug instructions in the issue template.
