### ISSUE TITLE
Did anyone make it on Windows 7 + gvim 8?

### ISSUE THREAD

**Issue by GIS-liuxl** [suan/vim-instant-markdown#117]
Hi all,

This project has won more than 1,500 stars! It means many of you are using this awesome plugin happily! I want to join you as well!

### System
```text
Win7 professional, SP1
vim: gVim 8.0.2
```
### Node.js
```text
node --version
v6.10.0
npm --version
3.10.10
```
I thought I installed the module successfully by:
```text
npm -g install instant-markdown-d
```
under Admin.

### curl
```text
curl --version
curl 7.53.1 (x86_64-pc-win32) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11 nghttp2/1.19.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz HTTP2 HTTPS-proxy
```
I putted the  instant-markdown.vim under `vimfiles\after\ftplugin\markdown` of my home folder `C:\Users\<me>` and created `C:\Users\<me>\_vimrc` as:

```vim
syntax on
filetype plugin indent on
```
But, when I open my `.md` file using gVim, there is no preview pop-up in my internet browser.

Could anyone can help me on this? Say, if you also has similar system settings with me and managed to install this plugin successfully, could you please give me a guidance about what did you do.

### Update (try vim-plug to install, didn't work)

I use [vim-plug](https://github.com/junegunn/vim-plug) to install plugin with `c:\Users\<me>\.vimrc`:

```vim
" Specify a directory for plugins
call plug#begin('~\vimfiles\plugged')

Plug 'suan/vim-instant-markdown' 

" Initialize plugin system
call plug#end()

filetype plugin on
```
After run `:PlugInstall` in gVim, it seemed that the plugin installed successfully, but still didn't work (internet browser didn't move).

bless~

**Comment by etherdrive** [comment]
I couldn't get it to work on windows until I tried this 
npm -g install https://github.com/suan/instant-markdown-d.git#master

**Comment by tpaixao** [comment]
Also not working for me. Using gVim 8.0 and windows 7

**Comment by ashwinvis** [comment]
Use master version or update to 0.1.1 or above from npmjs.com
