### ISSUE TITLE
Instant Markdown + Latex ?

### ISSUE THREAD

**Issue by jazzmess** [suan/vim-instant-markdown#119]
Hello everyone! Thanks for this awesome plugin, it's really useful.

I would like to know if there is a way to **display latex code** realtime (I'm currently using _Pandoc_ to render my markdown+latex files).

Cheers!

_PS: Not a native speaker, sorry for my English._

**Comment by patientCat** [comment]
MathJax can not works correctly after any modification for current file #67 
https://github.com/suan/vim-instant-markdown/issues/67
you can find the solution in the closed issues

**Comment by ashwinvis** [comment]
Fixed in #145 and suan/instant-markdown-d#53

**Comment by jcvillaquira** [comment]
Still not working for me :(

**Comment by ashwinvis** [comment]
@jcvillaquira Please submit a new issue with sufficient info.
