### ISSUE TITLE
GitHub Markdown Todo Item Support

### ISSUE THREAD

**Issue by sauhaardac** [suan/vim-instant-markdown#122]
In GitHub flavored Markdown, you can create todolists like the following:
- [ ]
- [x]
It would be nice if you could include this since you say you support GitHub flavored Markdown. Love your product!

Reference:
https://github.com/blog/1825-task-lists-in-all-markdown-documents

**Comment by ashwinvis** [comment]
Fixed in suan/instant-markdown-d#60
