### ISSUE TITLE
Opening new tab got E492: Not an editor command for InstantMarkdownPreview

### ISSUE THREAD

**Issue by krnl0138** [suan/vim-instant-markdown#123]
Hello, 
when i open file (which was created earlier) in new tab in vim with `.md` or `.markdown` ext via `:open ~PathToFile/File.md` or `NERDTree` or `Vimwiki` plugins, i get an error "E492: Not an editor command: InstantMarkdownPreview".
However, if i open those fiiles via terminal with `vim ~PathToFile/File.md`, everything works fine and i get my render in browser.
I don't change anything in instant-markdown plugin options.
`Vim v. 8.0.851, Pathogen`
What is it about?

Steps to reproduce:
1. Open file w/ .md ext (instant-markdown works fine)
2. In vim use `:open NewFile.md`
3. In vim use on new file `:InstantMarkdownPreview`

**Comment by githubzilla** [comment]
I have same issue when I type :MarkdownPreview, exactly as krnl0138 mentioned above.

**Comment by ashwinvis** [comment]
Pathogen is an outdated package manager. Can you try using [vim-plug](https://github.com/junegunn/vim-plug) as described in the readme?

**Comment by jojo253** [comment]
I installed the plugin with vim-plug and neither `:IntantMarkdownPreview` or `:MarkdownPreview` is valid command in vim. It seems the only way to open the preview is by `g:instant_markdown_autostart`.
By the way, you didn't provide a help file to refer by command like `:h instantPreview`.

**Comment by ashwinvis** [comment]
@jojo253 `:InstantMarkdownPreview` command is only available  if `g:instant_markdown_autostart=0`.

https://github.com/suan/vim-instant-markdown/blob/b3707e082df8843377475cb38a1fb9bb8f0d9315/after/ftplugin/markdown/instant-markdown.vim#L192-L208

 Help file is good point, feel free to open a separate issue.

**Comment by ashwinvis** [comment]
By the way, `:open` is not a vim command. Version info would be useful here.

**Comment by ashwinvis** [comment]
Fixed in #166
