### ISSUE TITLE
Not Working: Option Log Level is not Valid

### ISSUE THREAD

**Issue by randre03** [suan/vim-instant-markdown#126]
Hello, I've installed using the instructions on the README. When I open a markdown file, my browser (Firefox) pops open a new tab at localhost:8090, but nothing shows up.

I then tried `echo "lala" | instant-markdown-d`

Again, Firefox popped into view with new tab, but it was just reading and reading from "localhost". looking back at my terminal it was blocking with the following message: `Option log level is not valid. Please refer to the README.`

Not even sure which README I should be referring to. Thoughts?

Thanks in advance.

**Comment by tylucaskelley** [comment]
Same issue. On macOS 10.13 w/ Safari - I open a markdown file in Vim and a new browser tab opens, as expected, but I cannot connect to the server and there's no preview. When I run the `instant-markdown-d` command directly I get the same error message.

<img width="446" alt="screen shot 2017-12-04 at 7 53 38 pm" src="https://user-images.githubusercontent.com/5448759/33584349-e6ae103e-d92c-11e7-8a35-0b2ee28e000d.png">

**Comment by alexandre-floriano** [comment]
I'm also having the same issue (Ubuntu 16.04)

**Comment by amanusk** [comment]
@alexandre-floriano, @randre03, check what you get when you run `echo $BROWSER`

I had my `$BROWSER` variable set to `w3m`, which does not work. Setting it to firefox made it work. Hope this help :smile:

**Comment by gysddn** [comment]
I"ve experienced the same issue.

> @alexandre-floriano, @randre03, check what you get when you run `echo $BROWSER`
> 
> I had my `$BROWSER` variable set to `w3m`, which does not work. Setting it to firefox made it work. Hope this help

Sadly that didn't help, any other solution?

**Comment by asrmarco13** [comment]
Same problem. No solution yet?

**Comment by nytpu** [comment]
I ran into this problem while maintaining the AUR package, but it seems to be working fine now. Is everything upgraded to the newest version? If you need this specific version for some reason, this is what I used to fix it previously:

This is an issue with the upstream `socket.io`.  If you pin socket.io to version 0.9 it should work.

`patch "package/package.json" "pin-socket-io-version-at-0.9.patch"`  
pin-socket-io-version-at-0.9.patch
```
--- package.json    2015-01-18 04:14:05.000000000 +0100
+++ package.json    2019-03-24 20:27:57.818719661 +0100
@@ -13,6 +13,6 @@
     "highlight.js": "^8.4.0",
     "markdown-it": "^3.0.3",
     "send": "~0.1.0",
-    "socket.io": ""
+    "socket.io": "~0.9"
   }
 }
```

See cameel's comment on [this AUR package](https://aur.archlinux.org/packages/vim-instant-markdown/).

**Comment by ashwinvis** [comment]
@nytpu The last released instant-markdown-d is super old so don't rely on it for now.

**Comment by ashwinvis** [comment]
New versions are available now
