### ISSUE TITLE
open-to-the-world option does not work

### ISSUE THREAD

**Issue by MichaelMa2014** [suan/vim-instant-markdown#130]
I have already proposed a fix [here](https://github.com/suan/vim-instant-markdown/pull/129)

**Comment by hringriin** [comment]
I read your [fix](https://github.com/suan/vim-instant-markdown/pull/129) and the other comments, but neither replacing the lines with `let` nor the line with `call s:systemasync(env . 'instant-markdown-d', a:initialMDLines)` really works. On my local machine, I can see the correct page via `http://localhost:8090` or `http://<domain-name>:8090` without issues, but on other machines it seems that the content is not loaded. I get a kind of headline rectangle box with no content.

![Error in external browser][extbrowser]

[extbrowser]: https://download.barzh.eu/instant-markdown.png "Error in external browser"

**Comment by cobo920** [comment]
@hringriin Could you check the source code of the page? It seems npm version of instant-markdown-d tries to [connect to localhost](https://github.com/suan/instant-markdown-d/commit/b31c336146af4cd65d7d5ee931d48b0f1824fc18#diff-eacf331f0ffc35d4b482f1d15a887d3b). So after applying MichaelMa2014's [fix](#129), I installed github version of instant-markdown-d by `npm install -g suan/instant-markdown-d#master`, and now it worked.

**Comment by hringriin** [comment]
@cobo920 , you're right, it is connection to localhost.

Trying to (re)install via `npm install -g suan/instant-markdown-d#master` fails however, due to access restrictions. Sudo does not work either, so `npm install ...` has to be called directly as root.

Thank you :-)

**Comment by hringriin** [comment]
Ah, cheered too soon. Still get connection refused error from a remote machine. I *think* I put iptables out of the way. `iptables -L` outputs:

```
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```

I'm not too familiar with iptables, I have to admit. The source-code of the page on my localhost is fine, i.e. as it should be according to the fix.

I put `let g:instant_markdown_open_to_the_world = 1` in my vimrc, I set my firewall to allow every incoming traffic for the moment and I try to connect remotely via `http://<ip-address>:8090`

 Am I missing something?

**Comment by hringriin** [comment]
Nice :-)
