### ISSUE TITLE
github flavored markdown not supported

### ISSUE THREAD

**Issue by triplekiller** [suan/vim-instant-markdown#135]
The plugin does not support github flavored markdown syntax totally. For example:

**Task Todo:**                                                                  
- [ ] abc                                                                       
- [x] abcd                                                                                                                                             
**Extra Todo:**

The plugin will render the above as the following, it does not support checkbox.

Task Todo:
[ ] abc
[x] abcd
Extra Todo:

**Comment by ashwinvis** [comment]
The only way is to move instant-markdown-d 's CSS to something better supported, such as https://github.com/sindresorhus/github-markdown-css

**Comment by ashwinvis** [comment]
Fixed in suan/instant-markdown-d#60
