### ISSUE TITLE
Pending 5 min in Chrome when started

### ISSUE THREAD

**Issue by karajan1001** [suan/vim-instant-markdown#137]
About 3-4 weeks ago, when I opend localhost:8090 in my chrome , the page will pending for about 5 minute. Except this annoying pending, it works all well . When I opened developer tool, I found it was stuck in request `localhost:8090/ads.txt`. So I changed my browser to safari, and the question disappeared. And How can I make it work in chrome? My system is macOS Mojave

Thanks

**Comment by karajan1001** [comment]
Is there any method not to open the default browser? I want to set my default browser back to chrome. And choice safari to open when I opened a `.md` file.

**Comment by ashwinvis** [comment]
https://github.com/suan/instant-markdown-d/pull/24

**Comment by ashwinvis** [comment]
See #158
