### ISSUE TITLE
browser f5 refresh markdown preview is disappear

### ISSUE THREAD

**Issue by jiftle** [suan/vim-instant-markdown#139]
browser f5 refresh markdown preview is disappear

**Comment by ashwinvis** [comment]
This is strange. Can you run without vim, for example:

```sh
cat README.md | instant-markdown-d
```

and tell us what happens.

**Comment by jiftle** [comment]
vim is opened and click browser refresh button, then markdown preview page is disappear.  

![图片](https://user-images.githubusercontent.com/10773495/59756307-06f90200-92bc-11e9-943a-4fe65bf657c6.png)
![图片](https://user-images.githubusercontent.com/10773495/59756350-209a4980-92bc-11e9-8949-1397cc221887.png)
