### ISSUE TITLE
Links to other markdown documents?

### ISSUE THREAD

**Issue by fbicknel** [suan/vim-instant-markdown#155]
What's the secret to getting something like `<a href="A_Doc#place">this</a>` to work, where `A_Doc.md` is some other markdown document?

**Comment by ashwinvis** [comment]
See [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)

**Comment by fbicknel** [comment]
Soo.... this markdown:
`[FavoriteREPLs.md](FavoriteREPLs.md)`
and also
`[FavoriteREPLs.md](./FavoriteREPLs.md)`

... does indeed generate a link in the rendered page in my browser. But unfortunately when I click on that, I get a blank page with just this on it: `Not Found`

The URL changes to: `http://localhost:8090/FavoriteREPLs.md`.

The file (`FavoriteREPLs.md`) exists in the same directory with the file with the link source in it. So I assumed it should find it with relative reference mentioned in the cheatsheet.

Note that `FavoriteREPLs.md` renders nicely if I go to vim and use `:e<CR>`.

Also note that just going to `http://localhost:8090` from the browser renders a blank page only. In other words, once you click on the link, you can't go back to the page where the link lives.

Also note that links to anchors on the same page work as expected.

**Comment by ashwinvis** [comment]
What you should do is open the markdown, `FavoriteREPLs.md` inside vim. There is no two-way communication between vim and nodejs. That would be quite complicated.
