### ISSUE TITLE
Input error for small files

### ISSUE THREAD

**Issue by vpunch** [suan/vim-instant-markdown#168]
# Problem summary
I get errors on any input attempt if the file contains less than three rows. View in the browser works correctly anyway.

## Expected
Expect no errors.

## Environment Information
 * OS: Arch Linux
 * Vim / Neovim version: vim 8.1.1635
 * Browser: chromium

## Provide the debug output (required)
```sh
$ cat hello.md | instant-markdown-d --mathjax --debug
connection established! 
```

## Generate log files (required)
```
cat /tmp/instant_markdown.log

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8090: Connection refused
connection established!  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36    0     0    0    36      0  36000 --:--:-- --:--:-- --:--:-- 36000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```
I use the standard configuration (copy-paste from README).

## Steps to reproduce the issue (required)
Installed exactly as written in README.

To reproduce you need to create a new markdown file or edit it when it has less than 3 rows.

## Screen shot (if possible)
```
"hello.md" 2L, 26C
Error detected while processing function <SNR>38_pushMarkdown[4]..<SNR>38_bufGetLines:
line    6:
E684: list index out of range: -2
E116: Invalid arguments for function join([lines[row_num], '<a name="#marker" id="marker"></a>'], ' ')
Error detected while processing function <SNR>38_refreshView[2]..<SNR>38_bufGetLines:
line    6:
E684: list index out of range: -2
E116: Invalid arguments for function join([lines[row_num], '<a name="#marker" id="marker"></a>'], ' ')
```

**Comment by vpunch** [comment]
The error in this commit da10947728efe62f61626dcfe14100b26a77d0e0. If I get line 142 back in instant-markdown.vim, the error will disappear.

**Comment by nath1as** [comment]
same for me (latest arch, neovim, firefox nightly)

**Comment by ashwinvis** [comment]
@vpunch Thanks for debugging. I made that change to circumvent the issue in #154. We need a better fix then
