### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mettie** [suan/vim-instant-markdown#175]
When I open a markdown file my browser opens to the right address but doesn't display any of the contents of the file, only an empty box.  I turned on log output and a line in the log says
```
curl: (7) Failed to connect to localhost port 8090: Connection refused
```
This is on Mac OS Catalina with Vim 8.1 and Firefox.  I didn't use a plugin manager for installation, just cloned into ~/.vim/pack/md/start.  I tried using both the js server and the python one.  I also get the same result with "cat whatever.md | instant-markdown-d" (the browser opens but doesn't show the file)

**Comment by ashwinvis** [comment]
> I also get the same result with "cat whatever.md | instant-markdown-d" (the browser opens but doesn't show the file)

Which means it is an `instant-markdown-d` issue. Have you tried the `--debug` flag?

**Comment by Kish29** [comment]
I also have the same problem, have you solved it?

**Comment by mettie** [comment]
No sorry I kind of forgot to look into it further

**Comment by Kish29** [comment]
ok, emm, I checked the README.md, and I solved this problem, mistakes are:
   did not install nodejs   
   did not download the instant-markdown-d via npm
So, only copy or clone source code dosen't work
you have to download npm, and use npm to download instant-markdown-d.
you have to download xdg-utils, curl, nodejs if you're on linux
I use archlinux, I followed these steps:
    pacman -S curl
    pacman -S npm (download npm)
    pacman -S nodejs (download nodejs)
    pacman -S xdg-utils
    npm -g install instant-markdown-d

Add 'Plugin 'suan/vim-instant-markdown', {'rtp': 'after'}' into my .vimrc (I use Vundle to manage my vim plugins).
Re-open markdown file, and it works.

**Comment by ashwinvis** [comment]
I prefer to close this issue for now. If @mettie would like to pursue this further, we can re-open it.
