### ISSUE TITLE
firefox doesn't honor -p flag with vim-instant-markdown

### ISSUE THREAD

**Issue by cRaZy-bisCuiTs** [suan/vim-instant-markdown#176]
# Problem summary
When I set ....
` let g:instant_markdown_browser = "firefox -p app" `
...firefox launches the default profile instead of profile named app. If I type the same in the cli the correct profile is launched.
## Expected
The firefox profile "app" should be launched.

## Environment Information

 * OS: Ubuntu 19.10
 * Vim / Neovim version: 8.1
 * Browser: Firefox 73

**Comment by ashwinvis** [comment]
Should be fixed with #177
