### ISSUE TITLE
Can't Follow link in the preview page

### ISSUE THREAD

**Issue by strogiyotec** [suan/vim-instant-markdown#178]
Good day ,  thank you for this awesome plugin. I use it with vimwiki plugin.
I have a question about links in preview page.
Here is my folder structure
```
/vimwiki  ls
Algorithms.md  index.md  TimeComplexity.md
```
The content of index.md is 
```
[Algorithms](Algorithms) - Advanced Algorithms notes
```
As you can see it has a link to Algorithms.md file and when I press Enter(vimwiki binding) then I see the content of Algortihms.md file . However this feature doesn't work when I open preview page in browser. Algorithms is marked as a link but when I press this link it shows "**Not Found**" page.
But If I change the content of index.md to 
```
[Algorithms](Algorithms.md) - Advanced Algorithms notes
```
then when I click the link, browser tries to download a file.
Is there any way  I could open another link inside preview page ? Thank you

**Comment by ashwinvis** [comment]
You should open the new file in Vim instead :) Trying to do it from the browser would be really complicated. Maybe check out `smdv`, it might support this, but I am not sure.

**Comment by strogiyotec** [comment]
@ashwinvis  thank you for response
