### ISSUE TITLE
autoscroll does not work

### ISSUE THREAD

**Issue by sgon00** [suan/vim-instant-markdown#180]
# Problem summary

## Expected

Autoscroll should work. But when I move the cursor, the preview page does not move at all.

## Environment Information

 * OS: debian 10
 * Vim version: 2:8.1.0875-5
 * Browser: google-chrome
* instant-mardown-d version: v0.2.0-rc.2
* nodejs version: v14.3.0

**Comment by ashwinvis** [comment]
Thanks for the report

It needs enough content. So have you opened a long enough file? Please share `debug.html` as suggested in the issue template.

**Comment by sgon00** [comment]
@ashwinvis thanks a lot for the reply. 

I didn't provide other info because I didn't think they are useful. It just doesn't work at all. When I move the cursor to the end of the file, the scrollbar still remains at the top. I did create a long enough file. The scrolling will only work when I modify the file. I don't know if that is expected. From the README.md, what I expect is the scrolling should work when I move the cursor instead of modifying file at the cursor position. 

I am attaching debug.html now. It's just only `1`s in the file. 

[debug.html.zip](https://github.com/suan/vim-instant-markdown/files/4679591/debug.html.zip)

**Comment by ashwinvis** [comment]
> The scrolling will only work when I modify the file.
Yes this is intentional.
> From the README.md, what I expect is the scrolling should work when I move the cursor instead of modifying file at the cursor position.
I did not mention the cursor must be in insert mode, my bad.

You can see how it works here. The function which sends content with the cursor "marker" to the nodejs server.
https://github.com/suan/vim-instant-markdown/blob/2d5324edf171dd0cd2e1eb995fd77816ee3bb959/after/ftplugin/markdown/instant-markdown.vim#L147-L154

and the main function, which calls the function via temperedRefresh
https://github.com/suan/vim-instant-markdown/blob/2d5324edf171dd0cd2e1eb995fd77816ee3bb959/after/ftplugin/markdown/instant-markdown.vim#L208-L218

If you can make it work, I will gladly accept a pull-request.

**Comment by ashwinvis** [comment]
Actually, I am now unsure if this would even work at all. The docs for `CursorMoved` say

```
							*CursorMoved*
CursorMoved			After the cursor was moved in Normal or Visual
				mode or to another window.  Also when the text
				of the cursor line has been changed, e.g. with
				"x", "rx" or "p".
				Not triggered when there is typeahead or when
				an operator is pending.
				For an example see |match-parens|.
				Note: Cannot be skipped with `:noautocmd`.
				Careful: This is triggered very often, don't
				do anything that the user does not expect or
				that is slow.

```
which is not how it behaves.

**Comment by sgon00** [comment]
@ashwinvis 

Thanks a lot for the info. Yeah, I compared the beahviors between `let g:instant_markdown_autoscroll = 0` and `let g:instant_markdown_autoscroll = 1`. Autoscoll is actually working. When I disable the feature, the html view never scroll at all. When I enable the feature, the html view can scroll to the right position when I actually modify the file. So this is not an issue then. Just moving the cursor in any modes (including insert mode) will not trigger the autoscroll though, but that is expected based on the doc. I am closing this issue. Thanks.
