### ISSUE TITLE
I can't get images to show up

### ISSUE THREAD

**Issue by jonalvarado** [suan/vim-instant-markdown#34]
I would like to use relative images.  But even with an absolute path used I can't get it to work.

**Comment by codeHatcher** [comment]
+1

**Comment by lliseil** [comment]
+1 too. Here using vim-instant-markdown for viewing (and improve) a documentation directories tree. And its usability is rather lowered without images nor local links.

Maybe pull @frnsys implementation? Or @matthijskooijman's which seems to be clean and offers wider support?

**Comment by timball** [comment]
+1

**Comment by yech1990** [comment]
+1

**Comment by ngnmhieu** [comment]
+1

**Comment by bwangel23** [comment]
+1

**Comment by mwcz** [comment]
+1

**Comment by J-Razy** [comment]
+1

**Comment by jjery2243542** [comment]
+1

**Comment by drootang** [comment]
+1

**Comment by felixmokross** [comment]
+1

**Comment by stampedethegoat** [comment]
+2

**Comment by zhentao-huang** [comment]
+1

**Comment by ashwinvis** [comment]
Fixed in #60
