### ISSUE TITLE
Scroll to cursor/change

### ISSUE THREAD

**Issue by pdf** [suan/vim-instant-markdown#46]
Currently, when editing long documents, there's a lot of switching back and forth between the editor and browser to scroll to the part of the document you're editing, particularly if your'e making edits in various parts of the doc.

It would be super-handy to have the browser client either scroll to follow the line of output that matches the current cursor position in the source, or alternatively - since that may be somewhat difficult - scrolling on change would also be fine, so that the line currently being changed is always visible in the browser.

**Comment by qwIvan** [comment]
https://github.com/iamcco/markdown-preview.vim
This plugin can do this
