### ISSUE TITLE
Feature suggestion: Use pandoc as converter if present

### ISSUE THREAD

**Issue by thriveth** [suan/vim-instant-markdown#48]
I write quite a lot of scientific text, and Pandoc with its extended MarkDown has excellent support for some features that ordinary MarkDown oor GitHub-flavored MarkDown doesnẗ. On the other hand, I believe pandoc has support for most, if not all, GH flavored extensions. So maybe it would be great with an option to use Pandoc as the converting backend if it is installed on the user's system?

**Comment by shenxs** [comment]
@suan Sorry to brother but I still can't write scientific text such as `$x^2$`

**Comment by ashwinvis** [comment]
Now it supports mathjax in #145 and suan/instant-markdown-d#53. For pandoc, there is a dedicated vim plugin, see https://github.com/vim-pandoc/vim-pandoc

**Comment by thriveth** [comment]
Hi @ashwinvis  -- 

The Pandoc plugin you link - vim-pandoc -  is not a previewer, but an aid to write and edit Pandoc's Makdown flavor. 

This feature request was about adding the capability to preview Pandoc's Markdown flavor to vim-instant-markdown. This functionality is not and will not be covered by vim-pandoc.

**Comment by ashwinvis** [comment]
You are right, but does mathjax work for you, or you need pandoc specific stuff? If it is the latter, I will reopen the issue.

**Comment by ashwinvis** [comment]
Your [minimal example](https://github.com/suan/vim-instant-markdown/issues/48#issuecomment-36462970) is covered by mathjax. Also let me add that with `vim-pandoc`, you do get a `:Pandoc` command which is not "instant" but works pretty well to preview render. Just keep a PDF viewer open instead of the browser :)
