### ISSUE TITLE
Add error checking for external commands

### ISSUE THREAD

**Issue by dbarnett** [suan/vim-instant-markdown#75]
vim-instant-markdown silently ignores all shell command errors by using `:call system()` without ever checking v:shell_error. If anything goes wrong when running `curl` or `instant-markdown-d`, e.g. if the executables aren't even installed on `$PATH`, the user will have absolutely no feedback besides the fact that vim-instant-markdown silently fails to work as intended.

Could you add error handling to test `v:shell_error` and show `system()` output to users on error? Something like:

``` vim
let l:output = system(a:cmd)
if v:shell_error
  echohl ErrorMsg
  echomsg printf(
      \ 'ERROR in vim-instant-markdown: Failed to execute command "%s". Output was:',
      \ a:cmd)
  for l:line in split(l:output, "\n")
    echomsg '  ' . l:line
  endfor
  echohl NONE
endif
```

**Comment by ashwinvis** [comment]
We should have something like this, especially to get meaningful issue reports. A good implmentation is in [jedi-vim](https://github.com/davidhalter/jedi-vim/search?q=JediDebugInfo&unscoped_q=JediDebugInfo).
