### ISSUE TITLE
Escaping issue

### ISSUE THREAD

**Issue by oblitum** [suan/vim-instant-markdown#77]
Tried this but resulted in almost blank space when rendering because of inner `<` and `>` characters.

``````
```
HTTP/1.1 200 OK

Link: <https://foo.bar/v1/baz/123456?page=2>; rel="next",
<https://foo.bar/v1/baz/123456?page=3>; rel="last"
```
``````

**Comment by oblitum** [comment]
Using four space tabulation instead of fenced code blocks solved the display but because of that I'm having to mix fenced style and tabulation style for code blocks.

**Comment by ashwinvis** [comment]
It shouldn't be an issue if you specify


    ```sh 
    <https://foo.bar/>
    ```

or the target language instead of `sh`
