### ISSUE TITLE
Do you have a plan to add support for image link?

### ISSUE THREAD

**Issue by hitzhangjie** [suan/vim-instant-markdown#90]
Do you have a plan to add support for image link? I noticed that this plugin works well on Fedora21, except that it cannot handle image link properly.

**Comment by hitzhangjie** [comment]
I mean, the image link to local filesystems.

**Comment by timofurrer** [comment]
+1 on that one! Any plans?

**Comment by suan** [comment]
Yes! Working on other things right now (e.g. Windows support) but plan to
support this at some point

**Comment by jetsgit** [comment]
Any progress on image link for local files??

**Comment by msl-kabo** [comment]
Yeah, this would be nice. Working with [Gravizo](http://www.gravizo.com/#howto) images a.t.m. and it would be nice to see the images in there.

**Comment by MrFant** [comment]
It seems that the plugin still cannot support  the image link to local filesystems.
[![image](https://raw.githubusercontent.com/MrFant/MarkDownPhotos/master/image3.png)](https://github.com/MrFant/MarkDownPhotos/blob/master/image3.png)

**Comment by jetsgit** [comment]
I really needed image support for local filesystem, so I started using [Vim-livedown](https://github.com/shime/vim-livedown) which works great.

**Comment by JamesTiberiusKirk** [comment]
Hey guys, any update on this?
Is it still being worked on? I really need this feature.
Thanks.

**Comment by ashwinvis** [comment]
Fixed in #60
