### ISSUE TITLE
Is task list syntax supported？

### ISSUE THREAD

**Issue by zhenglaizhang** [suan/vim-instant-markdown#95]
I used following test snippet searched from google to check the task list syntax support.
It seems the companion page cannot render the task list correctly. Other common syntax rendering looks good.

Does the plugin supports tasklist syntax? Or is there any thing I need to reconfigure for my local env? Thanks in advance! 

I used zsh and .vimrc is updated per the readme.

------Testing snippets from google--------

```
### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune
- [ ] Comet Haley
```

**Comment by ashwinvis** [comment]
Fixed in suan/instant-markdown-d#60
