### ISSUE TITLE
Only works on readme.md files

### ISSUE THREAD

**Issue by abhixec** [suan/vim-instant-markdown#97]
I am unable to get this plugin to work with md files which aren't named `README.md` is this a known issue?

**Comment by taogashi** [comment]
Try `:verbose set filetype` in your vim, usually .md file is recognized as a modula2 file.  Just changing two lines in filetype.vim will make it work.

**Comment by suan** [comment]
@abhixec I re-added the reason why this happens on older Vim versions in [the FAQ](https://github.com/suan/vim-instant-markdown#faq)

Basically you either have to upgrade to vim version >= 7.4.480, or install a markdown plugin as as https://github.com/tpope/vim-markdown

Please re-open issue if it still doesn't fix it
